[theme]
primaryColor = "#6C5CE7"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 5
enableStaticServing = false

[browser]
gatherUsageStats = false
